Documentation update readme
DP6/adinfo-interface pull request #28
Opened 2022-08-24 20:12 UTC by LucasMachadodp6

Desenvolvimento da Documentação da interface do ADinfo.

2022-08-24 21:30 UTC, LucasTonetto requested changes

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +**ADInfo-interface** é a interface do [penguin ADinfo](https://github.com/DP6/adinfo-interface) ferramenta que foi desenvolvida para facilitar o controle e padronização do uso de parametrização e nom
- Usar "Adinfo" em vez de "ADInfo"
- Usar o link da API, não da interface
- "o permissionamento para controle de ações"
- Retirar o "e": permitidas por nível de acesso, o arquivo de parametrização

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +Nossa interface foi idealizada para **simplificar** e **otimizar** a parametrização de links de forma altamente costumizável, sendo uma ferramenta descomplicada de se utilizar e que irá centralizar d
- Substituir "Nossa interface" por "A interface"
- O que seria "centralizar de forma segura as informações de negócio"?

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +Por meio de controle de acessos, histórico de campanhas e versionamento de taxonomia, torna a interface do ADinfo muito amigável, visualmente simples e adaptável as necessidades de cada marca.
Acho que esse trecho pode retirar

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +( [Heroku](https://www.heroku.com/), [App Engine](https://cloud.google.com/appengine?utm_source=google&utm_medium=cpc&utm_campaign=latam-BR-all-pt-dr-SKWS-all-all-trial-e-dr-1011454-LUAC0008679&utm_c
- Tirar a vírgula antes do "em nuvem"
- Especificar o serviço da AWS onde poderia ser hospedado
- HostGator não é uma hospedagem em nuvem. Sugiro alterar o texto para "hospedagem" sem especificar o "em nuvem"

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +- API [ADinfo](https://github.com/DP6/penguin-adinfo#instala%C3%A7%C3%A3o) já hospedada;
- Mesmo ponto anterior, padronizar para "Adinfo"
- Existe um motivo para o link estar com âncora?

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +- Node a partir da versão 16;
Node versão 16 ou superior

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +A interface do ADinfo, é baseada em *Vue.js*, *Node.js* e *Html & Css*, atualmente esta sendo hospedada no *App Engine*, tendo as configurações de ambiente feitas por *App.yaml*.
Não mencionar que está hospedado no App Engine

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +Também contamos com *Babelrc* para transpilar códigos e manter a compatibilidade com navegadores.
Quem transpila o código é o Vue.js, não precisa especificar isso

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +Recomendamos fortemente o **Google App Engine**  como ambiente de hospedagem por ser uma opção com escabilidade autómatica, banco de dados e toda infraestrutura que apenas o Google pode oferecer.
- Retirar o "fortemente"
- O App Engine não possui banco de dados

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +Além disso ele permite que a aplicação seja executada em host local, e quando feita alterações, ele atualiza automaticamente em tempo real sem necessidade de reimplementar.
Retirar esse trecho, o appengine não faz isso

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> + **Após a instalação, será necessário apenas iniciar a interface executando os seguintes comandos :**
Tirar o "apenas"

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +*Instala as dependências para execução local:*
Instalar

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> + *Executa a aplicação em ambiente local(http://localhost:8080/):*
- Executar
- Retirar os parenteses e o conteudo dele

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +    nmp start
npm

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +### **1.1 Tipos de usuários**
Essa informação é da API, não? Não corresponde à interface

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +4. Logo abaixo na sub aba de Gerenciamento de Usuários também é possível ativar e desativar quais usuários terão acesso a plataforma de um modo bem eficiente.
- Incluir a vírgula em "Logo abaixo, na sub aba"
- Retirar o final "de um modo bem eficiente"

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +2. Em seguida a opção Template (1).
Acho que pode tirar as partes que estão "Em seguida" já que os steps já estão numerados

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +4. Após a conferência dos campos, realize o download do template em um dos dois formatos disponíveis, CSV ou XLSX (3).
CSV ou Planilha Excel (XLSX)

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +*Após o Download, as linhas devem ser preenchidas com as respectivas informações, necessárias para a geração do arquivo de parametrização.*
Retirar a vírgula.
"Informações necessárias"

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +7. E logo em seguida a mídia desejada.
Retirar o "E"

2022-08-24 21:30 UTC, LucasTonetto commented on README.md
> +*Após a parametrização, o Adinfo apresentará uma prévia das informações configuradas para revisão. Para consultar o resultado, selecione a opção Download Parametrização.*
Destacar ou colocar aspas em "Download Parametrização"

2022-08-25 14:13 UTC, LucasMachadodp6 commented on README.md
> +**ADInfo-interface** é a interface do [penguin ADinfo](https://github.com/DP6/adinfo-interface) ferramenta que foi desenvolvida para facilitar o controle e padronização do uso de parametrização e nom
os pontos observados foram corrigidos.

2022-08-25 14:17 UTC, LucasMachadodp6 commented on README.md
> +Por meio de controle de acessos, histórico de campanhas e versionamento de taxonomia, torna a interface do ADinfo muito amigável, visualmente simples e adaptável as necessidades de cada marca.
ok

2022-08-25 14:25 UTC, LucasMachadodp6 commented on README.md
> +- API [ADinfo](https://github.com/DP6/penguin-adinfo#instala%C3%A7%C3%A3o) já hospedada;
o Link ancora manda para a parte de instalação do Adinfo API, como a interface depende da API achei interessante colocar.

2022-08-25 14:29 UTC, LucasMachadodp6 commented on README.md
> +( [Heroku](https://www.heroku.com/), [App Engine](https://cloud.google.com/appengine?utm_source=google&utm_medium=cpc&utm_campaign=latam-BR-all-pt-dr-SKWS-all-all-trial-e-dr-1011454-LUAC0008679&utm_c
- HostGator removido 
- texto alterado para somente ''- Ambiente de hospedagem de aplicações. sugestão:''

2022-08-25 21:13 UTC, LucasMachadodp6 commented on README.md
> +7. E logo em seguida a mídia desejada.
pronto✔️

2022-08-25 21:13 UTC, LucasMachadodp6 commented on README.md
> +*Após o Download, as linhas devem ser preenchidas com as respectivas informações, necessárias para a geração do arquivo de parametrização.*
pronto✔️

2022-08-25 21:14 UTC, LucasMachadodp6 commented on README.md
> +*Após a parametrização, o Adinfo apresentará uma prévia das informações configuradas para revisão. Para consultar o resultado, selecione a opção Download Parametrização.*
pronto✔️

2022-08-25 21:14 UTC, LucasMachadodp6 commented on README.md
> +4. Após a conferência dos campos, realize o download do template em um dos dois formatos disponíveis, CSV ou XLSX (3).
pronto✔️

2022-08-25 21:15 UTC, LucasMachadodp6 commented on README.md
> +2. Em seguida a opção Template (1).
pronto✔️

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +**Adinfo-interface** é a interface do [penguin Adinfo](https://github.com/DP6/penguin-adinfo) ferramenta que foi desenvolvida para facilitar o controle e padronização do uso de parametrização e nomen
Colocar dois pontos depois de "Os principais componentes são"

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +A interface foi idealizada para **simplificar** e **otimizar** a parametrização de links de forma altamente customizável, sendo uma ferramenta descomplicada de se utilizar e que irá centralizar de **
Retirar esse trecho. Parece uma propaganda da interface. Tente manter uma linguagem mais técnica e explicativa

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +( [Heroku](https://www.heroku.com/),  [Google App Engine](https://cloud.google.com/appengine?utm_source=google&utm_medium=cpc&utm_campaign=latam-BR-all-pt-dr-SKWS-all-all-trial-e-dr-1011454-LUAC00086
Deixar na mesma linha da linha 15 e dar somente um espaço entre as opções

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +- Ambiente de hospedagem de aplicações sugestão:
A sugestão é apenas o AppEngine, vale citar as demais como "outras", mas não como sugestão

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +- Node a partir da versão 16;
- Node versão 16 ou superior

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +- Vue.js.
- Vue.js é um pré-requisito pro desenvolvimento da interface ou pra rodar tbm?

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +A interface do Adinfo, é baseada em *Vue.js*, *Node.js* e *Html & Css*, atualmente esta sendo hospedada no *App Engine*, tendo as configurações de ambiente feitas por *App.yaml*.
"A interface do Adinfo foi criada utilizando Vue.js, e hospedada no serviço App Engine do Google Cloud Platform. Todas as configurações de deploy da aplicação podem ser encontradas no arquivo App.yaml

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +Também contamos com *Babelrc* para transpilar códigos e manter a compatibilidade com navegadores.
Retirar. O Vue usa o Babel por baixo dos panos, não precisamos citar, já que não o usamos diretamente

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +Recomendamos fortemente o **Google App Engine** como ambiente de hospedagem por ser uma opção que requer o mínimo de configurações possíveis, com um serviço de plataforma completo e muita segurança d
Substituir esse trecho por: Para deploy da aplicação é recomendável o uso do serviço App Engine do Google Cloud Platform.

Tente evitar palavras como "recomendamos fortemente", não há algo que se recomenda fracamente. Geralmente só se usa "recomendar fortemente" pra dar mais ênfase, como essa é uma documentação técnica, não há necessidade disso.
Também evitar trechos que fazem propaganda sobre o Google Cloud, como "completo" "seguro" "simples" "eficaz", o intuito é só recomendar um ambiente de execução, a documentação é técnica, não há necessidade de expor qualidades do ambiente recomendado. O App Engine é recomendado simplesmente porque foi desenvolvido nele e conseguimos garantir a execução neste ambiente

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +Além destes pontos, basta apenas enviar o projeto para o App Engine que tudo deve funcionar e qualquer atualização será feita em tempo real sem a necessidade de reimplementação. Consequentemente, não
Retirar esse trecho.
Em geral, em documentações técnicas as explicações de deploy não são feitas em texto, apenas um passo a passo de como fazer o deploy é o suficiente

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +  **Requisitos Google App Engine:**
Retirar esse tópico de Requisitos Google App Engine.
Apenas faça uma lista de pré-requisitos e coloque o App Engine na lista

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +- altere o link de direcionamento da interface para API (caminho:  src > main.js);
quando estiver indicando diretórios, utilizar / em vez de >
src/main.js

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +**Após a instalação, será necessário apenas iniciar a interface executando os seguintes comandos :**
Retirar o negrito

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +*Instala as dependências para execução local:*
Instalação

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +*Executa a aplicação em ambiente local(<http://localhost:8080/>):*
Execução

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +## 1. Como adicionar novos usuários ao Adinfo
no Adinfo

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +1. Através de um usuário com permissão de Adimn, visite a aba de Usuários;
Com um usuário com permissão de Admin ou Owner, clique na aba de Usuários

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +
Acreidto que o step 2 seria clicar em "Registrar Usuário"

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +2. apos registrar usuários preencha os campos em aberto contendo o e-mail do novo usuário e a senha;
Preencha os campos em aberto

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +4. Logo abaixo na sub aba de Gerenciamento de Usuários também é possível ativar e desativar quais usuários terão acesso a plataforma de um modo bem eficiente.
Logo abaixo, na sub aba de Gerenciamento de Usuários, é possível ativar e desativar o acesso de usuários.

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +3. Ao clicar em criar, você receberá em resposta a senha de acesso. Com ela o novo usuário poderá utilizar a interface do Adinfo com acesso de Operação.
Todos itens da lista terminam com ;
Com exceção do último que termina com .

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +O primeiro passo do processo é a consulta e download do arquivo de preenchimento ou template. O template possui todas as informações definidas pelo Administrador como necessárias nos elementos de nom
URL

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +1. Para acessar o template configurado, selecione a opção Parametrizar no menu lateral.
Selecione a opção Parametrizar no menu lateral;

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +2. selecione a opção Template (1).
Todos itens começam com letra maiúscula e terminam com ;
O último item termina com .

2022-09-01 22:34 UTC, LucasTonetto commented on README.md
> +7. em seguida a mídia desejada.
Começar com letra maiúscula
Mesma observação sobre ; e . das demais listas

2022-09-02 13:39 UTC, LucasMachadodp6 commented on README.md
> +**Adinfo-interface** é a interface do [penguin Adinfo](https://github.com/DP6/penguin-adinfo) ferramenta que foi desenvolvida para facilitar o controle e padronização do uso de parametrização e nomen
ok✔️

2022-09-02 13:40 UTC, LucasMachadodp6 commented on README.md
> +( [Heroku](https://www.heroku.com/),  [Google App Engine](https://cloud.google.com/appengine?utm_source=google&utm_medium=cpc&utm_campaign=latam-BR-all-pt-dr-SKWS-all-all-trial-e-dr-1011454-LUAC00086
ok✔️

2022-09-02 13:40 UTC, LucasMachadodp6 commented on README.md
> +3. Ao clicar em criar, você receberá em resposta a senha de acesso. Com ela o novo usuário poderá utilizar a interface do Adinfo com acesso de Operação.
ok✔️

2022-09-02 13:41 UTC, LucasMachadodp6 commented on README.md
> +1. Para acessar o template configurado, selecione a opção Parametrizar no menu lateral.
ok✔️

2022-09-02 13:41 UTC, LucasMachadodp6 commented on README.md
> +7. em seguida a mídia desejada.
ok✔️

2022-09-02 13:42 UTC, LucasMachadodp6 commented on README.md
> +2. selecione a opção Template (1).
ok✔️

2022-09-02 13:42 UTC, LucasMachadodp6 commented on README.md
> +O primeiro passo do processo é a consulta e download do arquivo de preenchimento ou template. O template possui todas as informações definidas pelo Administrador como necessárias nos elementos de nom
ok✔️

2022-09-02 13:47 UTC, WernerAssis commented on README.md
> +- Ambiente de hospedagem de aplicações sugestão:
check

2022-09-08 14:26 UTC, LucasTonetto commented on README.md
>  Recomendamos fortemente o **Google App Engine** como ambiente de hospedagem por ser uma opção com escabilidade autómatica, banco de dados e toda infraestrutura que apenas o Google pode oferecer.
Retirar essa parte

2022-09-08 14:26 UTC, LucasTonetto commented on README.md
>  Além disso ele permite que a aplicação seja executada em host local, e quando feita alterações, ele atualiza automaticamente em tempo real sem necessidade de reimplementar.
Essa também

2022-09-08 14:26 UTC, LucasTonetto commented on README.md
>  após instalação e configuração execute no terminal:
Após

2022-09-08 14:26 UTC, LucasTonetto commented on README.md
> +Após a instalação, será necessário apenas iniciar a interface executando os seguintes comandos :
tirar o espaço antes dos :

2022-09-08 14:26 UTC, LucasTonetto commented on README.md
> +2. Clique em registrar usuário, preencha os campos em aberto;
2. Clique em registrar usuário e preencha os campos em aberto;

2022-09-08 16:06 UTC, closed without merging